version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TradSessions"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1erbhxwkwwi2a"
s3_prefix = "TradSessions"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

