AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A platform to find, share and review Irish traditional music sessions.

Resources:
  TradSessionsPublicEventService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: PublicEventService/
      Handler: public_event_service.public_event_handler
      Runtime: python3.7
      Policies: AmazonDynamoDBFullAccess
      Events:
        PublicEventServiceApi:
          Type: Api
          Properties:
            Path: /events
            Method: any

  TradSessionsEventTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: TradSessionsEventTable

  TradSessionsRankingTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: TradSessionsRankingTable
      PrimaryKey:
        Name: rank
        Type: Number

  TradSessionsUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: tradsessions
      UserPoolId: !Ref TradSessionsUserPool

  TradSessionsUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: TradSessionsUserPoolClient
      UserPoolId: !Ref TradSessionsUserPool
      GenerateSecret: false

  TradSessionsUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: TradSessionsUserPool
      AliasAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: False
      Policies:
        PasswordPolicy:
          MinimumLength: 7
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailSubjectByLink: 'Your TradSessions.ie Verification Link'
        EmailMessageByLink: 'Please click the following link to verify your email: {##Verify Email##}'

  TradSessionsPrivateEventServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: TradSessionsPrivateEventServiceApi
      StageName: Prod
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt TradSessionsUserPool.Arn
        AddDefaultAuthorizerToCorsPreflight: False
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'*'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"

  TradSessionsPrivateEventService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: PrivateEventService/
      Handler: private_event_service.private_event_handler
      Runtime: python3.7
      Policies: AmazonDynamoDBFullAccess
      Events:
        TradSessionsPrivateEventServiceApi:
          Type: Api
          Properties:
            RestApiId: !Ref TradSessionsPrivateEventServiceApi
            Path: /events
            Method: any

  TradSessionsUserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: TradSessionsUserTable
      PrimaryKey:
        Name: user
        Type: String

Outputs:
  TradSessionsPublicEventServiceApi:
    Description: 'Endpoint'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
  TradSessionsUserPool:
    Description: 'TradSessionsUserPool-ID'
    Value: !Ref TradSessionsUserPool
  TradSessionsUserPoolClient:
    Description: 'TradSessionsUserPoolClient-ID'
    Value: !Ref TradSessionsUserPoolClient
  TradSessionsPrivateEventServiceApi:
    Description: 'Endpoint'
    Value: !Sub 'https://${TradSessionsPrivateEventServiceApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
